# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU LGPL 3.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "nomorelevels" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "NoMoreLevels" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="NoMoreLevels.png" #optional
credits="@@@@@@@ - Commissioner"
authors="PugzAreCute"
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description = '''
Converts levels into exp points
'''
[[dependencies.nomorelevels]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nomorelevels]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nomorelevels]]
modId = "disenchanting"
mandatory = false
versionRange = "[2.2.0,)"
ordering = "BEFORE"
side = "BOTH"
