modLoader = "javafml" 
loaderVersion = "[43,)"
license = "GNU LGPL 3.0, https://www.gnu.org/licenses/lgpl-3.0.txt"
issueTrackerURL="https://github.com/PugsMods/NoMoreLevels/issues" 
[[mods]] 
modId = "nomorelevels" 
version = "${file.jarVersion}" 
displayName = "NoMoreLevels" 
#updateJSONURL="https://change.me.example.invalid/updates.json" 
displayURL="https://github.com/PugsMods/NoMoreLevels"
logoFile="Logo.png"
displayTest="IGNORE_ALL_VERSION"
credits="SdataG - Commissioner"
authors="PugzAreCute"

description = '''
Converts levels into exp points
'''
[[dependencies.nomorelevels]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nomorelevels]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.nomorelevels]]
modId = "disenchanting"
mandatory = false
versionRange = "[2.2.0,)"
ordering = "BEFORE"
side = "BOTH"
